apiVersion: v1
kind: ConfigMap
metadata:
  name: vulnerable-app-config
data:
  application.properties: |
    server.port=8080
    spring.application.name=vulnerable-app
    
    # H2 Database
    spring.datasource.url=jdbc:h2:mem:testdb
    spring.datasource.username=sa
    spring.datasource.password=password
    
    # Actuator
    management.endpoints.web.exposure.include=health,info,metrics
